#!/usr/bin/expect -f

set timeout -1

set workdir [lindex $argv 0];
set filename [lindex $argv 1];

spawn $workdir/liteclient-build/lite-client/lite-client -C $workdir/liteclient-build/ton-lite-client-test1.config.json
sleep 1
expect ""
send -- "sendfile $workdir/wrappers/$filename.boc\r"
sleep 1
send \x03
expect eof