#!/usr/bin/expect -f

set timeout -1

set filename [lindex $argv 0];

spawn /app/liteclient-build/lite-client/lite-client -C /app/liteclient-build/ton-lite-client-test1.config.json
sleep 1
expect ""
send -- "sendfile /app/wrappers/$filename.boc\r"
sleep 1
send \x03
expect eof